---
- hosts: pizerocluster
  tasks:
   - name: Rebooting nodes
     command: /sbin/shutdown -r now
     async: 1
     poll: 0
   - name: Store target host IP
     set_fact:
       target_host: "{{ ansible_host }}"
   - name: Wait for host to stop
     local_action: wait_for host={{ target_host }} delay=10 port=22 state=stopped timeout=120
